#!/system/bin/sh

if [ $MAGISK_MODULE_STATUS = "0" ]; then
    # Enable Google location accuracy
    settings put secure location_mode 3

    # Enable Wi-Fi scanning
    settings put global wifi_scan_always_enabled 1

    # Enable Bluetooth scanning
    settings put global ble_scan_always_enabled 1

    # Set mock location app to GPS Joystick
    settings put secure mock_location_app "com.theappninjas.fakegpsjoystick"
else
    # Disable Google location accuracy
    settings put secure location_mode 0

    # Disable Wi-Fi scanning
    settings put global wifi_scan_always_enabled 0

    # Disable Bluetooth scanning
    settings put global ble_scan_always_enabled 0

    # Clear mock location app setting
    settings delete secure mock_location_app
fi
